name: Test build now comment build jr.

on: 
  pull_request:
    branches: [main]
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comment_check2:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'build now'
      - name: Fail
        if: ${{ steps.check.outputs.triggered == 'false'}}
        run: exit 1
      - name: Test
        if: ${{ steps.check.outputs.triggered }}
        run: echo "I DID IT!"