name: Test buid now comment build

on: 
  pull_request:
    branches: [main]
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comment_check:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'build now'
  post_comment_check:
    runs-on: ubuntu-latest
    needs: comment_check
    if: ${{ needs.comment_check.outputs.triggered == 'true' }}
    steps:
      - name: Test
        run: echo "I DID IT!"